version: '3'
services:
    planet-api:
        build:
            context: ./backend
            dockerfile: ./docker-backend.dockerfile
        volumes:
            - ./backend:/app
        restart: always
        ports:
            -   "3001:3002"
        deploy:
            mode: replicated
            replicas: 1
        environment:
            EMAILFROM: ""
            EMAILTO: ""
            APPPASS: ""

    frontend-service:
        build:
            context: ./frontend
            dockerfile: ./docker-frontend.dockerfile
        # volumes:
        #     - ./frontend/.output:/app
        restart: always
        ports:
            -   "3002:3000"
        deploy:
            mode: replicated
            replicas: 1
